version: "3.8"

services:
  wp:
    container_name: ${DOMAIN}_wp
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    ports:
      - 80:80 # change ip if required
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      # - ./wp-app:/var/www/html # Full wordpress project
      - ./themes/${PARENT_THEME}:/var/www/html/wp-content/themes/${PARENT_THEME} #master template
      - ./themes/${THEME}:/var/www/html/wp-content/themes/${THEME}

    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: | # Add config to wp-config.php
        define('FS_METHOD', 'direct');
        define('WP_DEBUG_LOG', true);
        define( 'WP_DEBUG', true );
    depends_on:
      - db

  # wpcli:
  #   container_name: ${DOMAIN}_wpcli

  #   image: wordpress:cli
  #   volumes:
  #     - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
  #     - ./wp-app:/var/www/html
  #   depends_on:
  #     - db
  #     - wp

  db:
    container_name: ${DOMAIN}_db
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - ${IP}:3306:3306 # change ip if required
    command:
      [
        "--default_authentication_plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
  pma: # add phpmyadmin
    image: phpmyadmin/phpmyadmin
    container_name: ${DOMAIN}_phpmyadmin
    restart: always
    ports:
      - "8000:80"
volumes:
  db_data:
    name: ${DOMAIN}_db
